using System;
using System.Collections.Generic;
using System.Linq;
using ManyConsole;

namespace monarquia
{
	public class ViewExercises : ConsoleCommand
	{
		public bool LimitOutput;
		public bool UseBiggerCannedData;

		public ViewExercises ()
		{
			this.IsCommand ("view-all-exercises", "List all exercises generated by BetterCannedData.");
			this.HasOption ("z", "Reduces permutations in various ways.", v => LimitOutput = true);
			this.HasOption ("b", "Uses bigger canned data.", v => UseBiggerCannedData = true); 
		}

		public override int Run (string[] remainingArguments)
		{
			DataLoader dataLoader = new DataLoader("./data");
			var cannedData = new BetterCannedData (dataLoader);

			if (UseBiggerCannedData) {
				cannedData = new BigCannedData (dataLoader);
			}

			var exerciseGenerator = new EspanolGenerator (cannedData, "./data");

			List<ExerciseGenerator.Exercise> results = new List<ExerciseGenerator.Exercise> ();

			results.AddRange (exerciseGenerator.GetExercises (null, LimitOutput));

			foreach (var exercise in results) {
				Console.WriteLine (exercise.Original);
				Console.WriteLine (exercise.Translated);
				Console.WriteLine ("{0} - {1}", exercise.ExtraInfo, String.Join(", ", exercise.Tags));
				Console.WriteLine("");
				Console.WriteLine("");
			}

			return 0;
		}
	}
}

