using System;
using System.Collections.Generic;
using System.Linq;
using ManyConsole;

namespace monarquia
{
	public class ViewExercises : ConsoleCommand
	{
		public bool LimitOutput;

		public ViewExercises ()
		{
			this.IsCommand ("many-exercises", "List all exercises generated by BetterCannedData.");
			this.HasOption ("z", "Reduces permutations in various ways.", v => LimitOutput = true);
		}

		public override int Run (string[] remainingArguments)
		{
			var cannedData = new BetterCannedData ();

			var exerciseGenerator = new EspanolGenerator (cannedData, "./data");

			List<ExerciseGenerator.Exercise> results = new List<ExerciseGenerator.Exercise> ();

			foreach (var verb in BetterCannedData.BetterVerbs) {
				results.AddRange (exerciseGenerator.GetForVerb (exerciseGenerator.LookupVerb (verb), LimitOutput));
			}

			foreach (var exercise in results) {
				Console.WriteLine (exercise.Original);
				Console.WriteLine (exercise.GetTranslatedWithHints());
				Console.WriteLine ("{0} - {1}", exercise.ExtraInfo, String.Join(", ", exercise.Tags));
				Console.WriteLine("");
				Console.WriteLine("");
			}

			return 0;
		}
	}
}

